title: Petr Janík
name: Petr Janík
email: peta.janik@email.cz
description: Hi! I'm a student of applied informatics at Masaryk University in Brno. I love coding, especially in Python. I've got experience with other programming languages and tools, such as Java, Android Studio, C and Git. 

baseurl: "/blog"
url: ""

parallax_image_one: assets/images/startup3.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup3.jpg

project_one: SoloLearn Coding Challenges
project_one_description: This is my favourite educational site. I've completed most of the challenges and here are the solutions.
project_one_url: https://github.com/petr7555/Coding-challenges
#project_one_icon: location_on

project_two: Sklenda Python Game
project_two_description: A fun game for two players. Created in Python 3 using pygame library. Rules are similar to tic-tac-toe, but a little bit more advanced (see github readme file).
project_two_url: https://github.com/petr7555/Sklenda-pygame



project_three: Spreadsheet Notification Macro
project_three_description: I created this form in Google Spreadsheets so that our coaches would have an easy way to let us know that the time of lesson has changed. It is supposed to be right next to the schedule. It also has second list, which contains names and email addresses. A coach fills in names, day and time and hits send button. A notification pops up to let him know that the message has been sent successfully.
project_three_url: https://github.com/petr7555/Google-spreadsheets-notification-form-and-macro



project_four: Court Counter Java App
project_four_description: An app created in Android Studio that counts score in basketball.
project_four_url: https://github.com/petr7555/CourtCounter-java-app


project_five: Coffee-ordering Java App
project_five_description: An app created in Android Studio that orders coffee via email.
project_five_url: https://github.com/petr7555/JustJava-java-app

project_six: Python Terminal Games
project_six_description: Fun games you can play in the terminal. Includes chrome-like dinosaur and tic-tac-toe.
project_six_url: https://github.com/petr7555/Python-games

project_seven: History of Super Powers
project_seven_description: A website that contains a timeline of main historical events of each of eight chosen countries. Furthermore, there is a fun JavaScript quiz.
project_seven_url: https://petajanik.wixsite.com/velmoci


portfolio_heading: Portfolio
portfolio_type: cards

syntax_highlighting: true
# Skill icons from https://konpa.github.io/devicon/

skills:
  #- name: amazonwebservices
  - name: android
  #- name: angularjs
  #- name: apache
  #- name: appcelerator
  #- name: apple
  #- name: atom
  #- name: babel
  #- name: backbonejs
  #- name: bitbucket
  #- name: bootstrap
  #- name: bower
  - name: c
  #- name: chrome
  #- name: codeigniter
  #- name: coffescript
  #- name: confluence
  #- name: cplusplus
  #- name: csharp
  - name: css3
  #- name: cucumber
  #- name: d3js
  #- name: debian
  #- name: devicon
  #- name: django
  #- name: docker
  #- name: doctrine
  #- name: dot-net
  #- name: drupal
  #- name: erlang
  #- name: facebook
  #- name: firefox
  #- name: foundation
  #- name: gatling
  #- name: gimp
  - name: git
  - name: github
  #- name: gitlab
  #- name: go
  #- name: google
  #- name: gradle
  #- name: grunt
  #- name: gulp
  #- name: heroku
  - name: html5
  #- name: ie10
  #- name: illustrator
  #- name: inkscape
  #- name: itellij
  - name: java
  #- name: jasmine
  - name: javascript
  #- name: laravel
  #- name: less
  #- name: linux
  #- name: meteor
  #- name: mocha
  #- name: mongodb
  #- name: moodle
  #- name: mysql
  #- name: nginx
  #- name: nodejs
  #- name: nodewebkit
  #- name: oracle
  #- name: photoshop
  #- name: php
  #- name: phpstorm
  #- name: protractor
  #- name: postgresql
  - name: python
  #- name: pycharm
  #- name: rails
  #- name: react
  #- name: redhat
  #- name: redis
  #- name: ruby
  #- name: rubymine
  #- name: safari
  #- name: sass
  #- name: sequelize
  #- name: slack
  #- name: sourcetree
  #- name: ssh
  #- name: swift
  #- name: symfony
  #- name: tomcat
  #- name: travis
  #- name: trello
  #- name: twitter
  #- name: typescript
  #- name: ubuntu
  #- name: vim
  #- name: visualstudio
  #- name: vuejs
  #- name: webpack
  #- name: webstorm
  #- name: windows8
  - name: wordpress
  #- name: yii
  #- name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/petr7555/
medium: https://medium.com/@petrjanik

baseurl: # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

# Google tracking, if both are filled, tag manager will prevail. Set up GA through GTM in that case
tag_manager_id: # This looks something like GTM-XXXXXXX
google_analytics_tracking_id: UA-120550924-1 # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

syntax_highlighting: true # include the css for syntax highlighting

# Build settings
markdown: kramdown
# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
